language: node_js
node_js:
- node
before_script:
- npm install
script:
- npm run build
deploy:
  provider: pages
  local_dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master